### ISSUE TITLE
deepnlp

### ISSUE THREAD

**Issue by zhangweiwei0512** [rockingdingo/deepnlp#1]
您好，我关注了您并且开始使用deepnlp，但在使用过程中遇到一些问题，可否告知QQ向您请教，感激 @rockingdingo 
我的QQ438942304

**Comment by rockingdingo** [comment]
好的, okay, 也可以邮件沟通啊

**Comment by rockingdingo** [comment]
Release deepnlp 0.1.5
Fix below issues

Fix 1:  python2 and python3 compatibility issues

# python2 adding __future__ module
# compatible with python3 unicode coding
from __future__ import unicode_literals

Fix 2: Adding absolute import from py3

from __future__ import absolute_import
from pos import pos_model
