### ISSUE TITLE
能否提供一下ner中训练用的语料库

### ISSUE THREAD

**Issue by strayly** [rockingdingo/deepnlp#14]
能否提供一下ner中训练用的语料库数据，非常感谢

**Comment by zhuanxuhit** [comment]
这个命名实体识别的语料是用的哪个？

**Comment by rockingdingo** [comment]
@strayly @zhuanxuhit    原先的标注语料是在数据堂获得的 http://www.datatang.com/datares/go.aspx?dataid=617173  ，ITNLP中文命名实体标注数据（160万词），http://www.datatang.com/datares/go.aspx?dataid=617173，但是貌似现在被下架了。可以邮件单独联系哈。

**Comment by zbtong** [comment]
hi，我最近也在做中文命名实体识别的研究，请问可以发我一份语料吗？邮箱zbtong1994@gmail.com，万分感谢！
