### ISSUE TITLE
TypeError: in method 'Tagger_add', argument 2 of type 'char const *'

### ISSUE THREAD

**Issue by lstmabc** [rockingdingo/deepnlp#29]
问题怎么解决？谢谢了。

**Comment by jotline** [comment]
同问啊

**Comment by jotline** [comment]
解决了，换成python2.7就没问题了

**Comment by BrightXiaoHan** [comment]
能在python3上运行吗

**Comment by rockingdingo** [comment]
@lstmabc @jotline @BrightXiaoHan  修改了一下可以在 python3 上跑了， 因为 2和3的str类型不同，修改的地方是, 加了版本的判断, python3 不需要encode :

`        for char in text.strip(): # char in String
            char = char.strip()
            if char:
                input_char = (char + "\to\tB").encode('utf-8') if (version_info == "py2") else (char + "\to\tB")
                model.add(input_char)`

**Comment by Alucardmini** [comment]
https://github.com/rockingdingo/deepnlp/issues/29#issuecomment-353294778 正解
