### ISSUE TITLE
Use tensorflow1.0 cause error

### ISSUE THREAD

**Issue by endymecy** [rockingdingo/deepnlp#3]
I use deepnlp branch is 0.1.5 and this version is not support tensorflow1.0

AttributeError: 'module' object has no attribute 'rnn_cell'.

**Comment by endymecy** [comment]
And there is not 0.1.6 package in https://pypi.python.org/pypi/deepnlp

**Comment by rockingdingo** [comment]
Hi endymecy, Thanks for letting me know. Yes, Tensorflow 1.0 changed several functions and previous models are not reusable. I am still training new models based on the tensorflow 1.0 functions. Now in the repo POS/NER are already up to date. You can give it a try and I will soon release 0.1.6 once I finished training other models.

**Comment by hitluobin** [comment]
miss the same problem, hope rockingdingo fix soon, thank u

**Comment by rockingdingo** [comment]
Hi @endymecy @hitluobin, Thanks for letting me know.  I just released the 0.1.6 version today, which is now compatible with tensorflow 1.0 functions. Please let me know if it works.

**Comment by endymecy** [comment]
now it is ok
